"""add doc_type to files and skipped_doc_types to projects

Revision ID: 5fad8e9a85f3
Revises: a7b46367f8f0
Create Date: 2026-03-22 09:05:11.900194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fad8e9a85f3'
down_revision: Union[str, Sequence[str], None] = 'a7b46367f8f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('doc_type', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_files_doc_type'), 'files', ['doc_type'], unique=False)
    op.add_column('projects', sa.Column('skipped_doc_types', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'skipped_doc_types')
    op.drop_index(op.f('ix_files_doc_type'), table_name='files')
    op.drop_column('files', 'doc_type')
    # ### end Alembic commands ###
